syntax on
colorscheme ron
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set autoindent

set lbr
set number
highlight LineNr ctermfg=grey

nnoremap <F4> :! clear && gcc % && clear && ./a.out<cr>
